---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nextcloud
spec:
  interval: ${helm_repo_interval:-${global_interval:-10m}}
  url: https://nextcloud.github.io/helm/
