apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdtd-server
  labels:
    app: sdtd-server
  namespace: sdtd-server
spec:
  template:
    metadata:
      name: sdtd-server
      labels:
        app: sdtd-server
    spec:
      initContainers:
        - name: init-permissions
          image: busybox
          command: ["sh", "-c", "mkdir -p /home/steam && chown -R 1000:1000 /home/steam"]
          volumeMounts:
            - mountPath: /home/steam
              name: sdtdserver-data
      containers:
        - name: sdtd-server
          image: kubelize/sdtd-server:0.1.2
          # command: ["/usr/bin/sleep", "infinity"]
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "6Gi"
              cpu: "2"
            limits:
              memory: "8Gi"
              cpu: "4"
          ports:
            - containerPort: 26900
              protocol: TCP
              name: gameport1tcp
            - containerPort: 26900
              protocol: UDP
              name: gameport1udp
            - containerPort: 26901
              protocol: UDP
              name: gameport2udp
            - containerPort: 26902
              protocol: UDP
              name: gameport3udp
            - containerPort: 8080
              protocol: TCP
              name: webadmin
            - containerPort: 8081
              protocol: TCP
              name: telnet
          volumeMounts:
            - mountPath: /home/steam/sdtd/
              name: sdtdserver-data
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
      volumes:
        - name: sdtdserver-data
          persistentVolumeClaim:
            claimName: sdtdserver-data
  replicas: 1
  selector:
    matchLabels:
      app: sdtd-server
