apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
  labels:
    name: pihole
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: pihole
  sources:
    - repoURL: https://github.com/kubelize/kube-projects
      targetRevision: dev
      path: base/incubator/pihole/deploy
    - repoURL: https://mojo2600.github.io/pihole-kubernetes/
      targetRevision:  2.27.0
      chart: pihole
      helm:
        parameters: []
        valuesObject:
          persistentVolumeClaim:
            enabled: true