apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 

# incubator
# - ../../../base/incubator/test-nginx/

# stable
# - ../../../base/stable/nextcloud/
- ../../../base/stable/gameservers/minecraft-vanilla/
- ../../../base/stable/gameservers/web-rcon/
- ../../../base/stable/uptime-kuma/

# secrets
- secrets/minecraft-rcon-password.yaml
- secrets/cf-api-token.yaml

# patches:
#   - path: ./patches/example/example.yaml
