apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []

# incubator
# - ../../../base/incubator/test-nginx/

# stable
# - ../../../base/stable/nextcloud/

# patches:
#   - path: ./patches/example/example.yaml
