apiVersion: v1
kind: Service
metadata:
  name: rickroll
  namespace: rickroll-heyya-immobilien-ch
  labels:
    app: rickroll
spec:
  selector:
    app: rickroll
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP