apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: itzg-minecraft
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: minecraft
  source:
    repoURL: https://itzg.github.io/minecraft-server-charts/
    targetRevision: 4.19.0
    chart: minecraft
    helm:
      parameters: []
      valuesObject:
        image:
          repository: itzg/minecraft-server
          tag: latest
          pullPolicy: IfNotPresent
        replicaCount: 1
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
        minecraftServer:
          eula: "TRUE"
          # One of: LATEST, SNAPSHOT, or a specific version (ie: "1.7.9").
          version: LATEST
          # This can be one of "VANILLA", "AUTO_CURSEFORGE"
          type: "VANILLA"
          serviceType: LoadBalancer
          servicePort: 25565
          rcon:
            enabled: true
            withGeneratedPassword: false
            port: 25575
            existingSecret: minecraft-rcon-password
            secretKey: rcon-password
            serviceType: ClusterIP
          autoCurseForge:
            apiKey:
              existingSecret: "cf-api-token"
              secretKey: cf-api-key
            # Link to modpack page on CurseForge, example: https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/download/5564373
            pageUrl: ""
            # Less restrictive way of specifying modpack version, uses substring match example: "1.16.5"
            filenameMatcher: ""
        persistence:
          storageClass: "longhorn"
          dataDir:
            enabled: true
            Size: 10Gi
            accessModes:
              - ReadWriteOnce