apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sdtd-server
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/kubelize/kube-projects
      path: 00_base/stable/gameservers/sdtd
      targetRevision: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: sdtd-server