apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: keycloak  # Same namespace as the secret
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
