apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rickroll-heyya-immobilien-ch
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/kubelize/kube-projects
      path: base/incubator/rickroll-heyya-immobilien-ch/deploy
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: rickroll-heyya-immobilien-ch