---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-database-credentials
  namespace: keycloak
spec:
  encryptedData:
    postgres-password: AgBhafiriG9ulL+Y0qdfWsLlyhhQo++WUDRgc3BHYsuGywPp9upXRNY3BhIo0VmYNT7XC9RmwJb/aKcGuyVF98xPbrOiPtEZjkooHGqoUqUl9aXb3KacQDPC4HPVF3kmrxbyo106FME5gZWsO8MaeM6FSqBH99JRhRF1QyAyCFLnLfrRr3MNtzqCeSaPvFJgCDqI4NAN39FGT58RqhLDiki641xOjjADMaHjynoC8wm1TcS2UKbe2lt3Faj3c3HMAXX9Dqcz8G9UBXF2l41DXvg4sUmoey76nxDn11X1asAu/15cHZneuvUGXG0hMXHNzb369+ZIfsGdP2kNe7dBDld7e8i0r3zrlu6fj2lnPCykFU/kFNWRCvbiT1+ivYdaI/NfQGpOOplTn1b8cd3CJHSS3JG3co4//kep4TBqTjV3zTp+XOfTa3HZeIYlqSUV5sNxvT0Oasj/f7GJ3jl2+yInur6AwxA9xUWO6xwXMU0UDEnBV8eD2L9Xxw9m+yEz4JQPkkNv9/zICrwZx2Z231d/ybfmo0HND4AEKiEIomta8zU/X++KMmbBvnAOqnNxLVaRhSEQezbfEbEcMifd+oDmFd+v6DgvBsFaW6QHqUp9NTRkWipFDmMzKhdXFix5nHi5OHoNUu9jvxOX72DdX2LvsaPMxX7HttAtQziqfnOOyIIQR3Q9YBhnPOqdHoLH56W9vuRC/jY7I2Ee7cCahcAWwmZ9zH6kWJmS
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-database-credentials
      namespace: keycloak
    type: Opaque
