---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-admin-credentials
  namespace: keycloak
spec:
  encryptedData:
    password: AgBbg+e2AwrImdQZeAIxrnEFnij2ehO8UwmsjyBXXo520lY16HWfK73ubgbINA7ux+x9ZE48bYI3CGZTn8WzQZHMUmMZyjnG1j2q/9ZmJFFcdRdTTVYFjF/7zAgfHXO99DA8pB/pjSEQeixyMt819F7EecbGBUfGS1fq6hTeZkW9VxhEWL4oQ9DJWKNiXQ0W1Bu2jDB9kdI4A9SN3ZGjxy2t/UlYvyO0ybc/rwI0eNnZDuiDMsQgUtZ/qfjuYQluEBDdvsndG+WnTTsfDgTjyjtkJ+1kxlVsptk9VginqMytTEGCYpvsHIDjlsDVm44rMy9cZCJ36YHpkz4/d4nQd3GxAHGb1aqBVzBqBSgQE33JnM/9G6md8hitNoZqYAIG0JzgwS0VhS6Oa0sd32jxNLnZlncFrJ+Q4q2HQEOKEPP8CiggZvavODKz2aAODsryRhhKCXqB1yN6wdhYUioMaTOXLwgB2F4Vzs6rWV+AlouSbnIPKgsDbuSAj6BgheT3AKir+/i/2MuXk2hCZ2/pP6NzTJF+pxpmrSj6dHFCeWtVvbeh8MWfGhi5fXtcHUI9QSRIk1EEOGyKK5lpJSFCR31SVyzWVzwtMPUTSz1vPidjSqZpFc49XGfL0WgB9SWjXqzjyApiV7AqaJpqjJ7e7lZVK2fUaW4UqSD5ucAqfyOo9XJDIJiG2KAvFt4wT3lEKqu5V9l9D8W03gg+Llf0f2K1vMlP+Q==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-admin-credentials
      namespace: keycloak
    type: Opaque
