---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-admin-credentials
  namespace: keycloak
spec:
  encryptedData:
    password: AgCVDgg1iljEg917iH6PBqIxTEeCder+dz3y4HA3nTCX8skFb9D3eJsRnjjmkDHLybcd1KqU0idvoNsWRTzdIYp9OhKqBMzrbkDyO2b+RLkRIJB7MhSw6yX544aq7WltsmHmD7a8oJ3tU3LmKqgcVEafBtQezOgHvmOnoEhYU2E+z1IOuLu3wOptfVdu7Z53KjhecYjp8qeorR120yVE0upGQ4qTspb1JnyqTb6GiXVOdAl1bY3bLmwN6V/tsg9a4qFj3QsfsEqy8A8eU1tvTsk7NPdjH3BmKVvYtUYetACt8eRuhOK+Q0ZbrtCB+8+cSq3FcDOLxjeJMSHHwJrwObGTDnp9/yiz6xdQ6UWOfNLBJbce2BqjHxp2Dx6f0K86WRzzKN8Z/xwhKsaffRCWTFOAeOEy+kGyog5qR43tYFDFcQgeo/bf0CjEIMn3tZD4lC6EkjM873r3Yl99uPKnMELHKtDBup6WrfPfwyRp0nfmYXFUZjhprNa0NzCoxzwPtnN+gwxsYFZ53oikjmQWodi9IegLonX9Yx4a2z20YLQHvGDiIe/zUTmHalKLiNvZZ4bVjFdZbQdLlPRHNPQDAnTUF5C3ciOi3dDYtqEw15MJ0bns6/lscoPyNN7635iXpGe4CClNnEuTw9clerJpkqivWFjATStwKNPgRS7jGG2DIMzSBfvcwsU/5UUgwwtMk1LLXdBOS0dUoGIPLCkwixgw799h
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-admin-credentials
      namespace: keycloak
    type: Opaque
