---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-database-credentials
  namespace: keycloak
spec:
  encryptedData:
    password: AgBqaOBYY0IBY5NqeMReE31ar6IoLAi1NXc19lcH5+2WqsQkRwcMus1PTxcrERLC5CLVI5BPJ4XDn6qw+4ISp+cufJBtZFyYpP1KZOtht/jNrcJtoL3leuVpJel6MZhtqx9ewxtfpnfY1lBjLkvFhj2wiZQCizJQBC/AMbdGsRgymKeUDkspgdiL1Vd1n67YbWrUl4OqZavttwhwa8PUQSEE57oO9LabQB6ye0C3gyDOuItbzjkiutO0A1q8fc6U9FTU8kMavWyF6yYlRSeyX29KcP0WkToM9pQh7PBrP6kzEKvWOn28PRnsNrT7vR3H4BVTTPzJmu6Kp5eUJ/URrPXW/faCtfxEIIkVuehNAE6eUhF/++rDgIAI+b2uPnsdpi/stAXkCYGpQ3JGfxCdD8uqNbJ5BdU1v8J/3TvdkK0hBBPQOyfWectwd4dljYQoa3LRChsNsNFbs/JkX/WeERQLQhDb76yD7j2XTiK7xFRIywn1/I5xH0A1ZA0rQ+GP2hmrWF4f/2ACZbrsDYs/YkaGbQPtJ2XEw+9vGWAaDjXQt83HL2POy18qqhaMhUXJ9QVJeWTUrzKPl7Taufy8XxxOyYBcPKAU6m+dEzUFOnJSGw3cFM/M/4k4AOsY9wDQEVuAtDMpehuD0ftyCH2m9PY2L2ZscP00Ef0cGauV5+9U2KfKOp2J1X7ASD6tuNUWo3j0veCnDcTRUQko2F4JpNMWVu7HVg5nYfA8
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-database-credentials
      namespace: keycloak
    type: Opaque
