apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian-migrate-pvc
  labels:
    app: debian-migrate-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debian-migrate-pvc
  template:
    metadata:
      labels:
        app: debian-migrate-pvc
    spec:
      containers:
      - name: debian
        image: debian:latest
        command: ["/bin/sleep", "infinity"]  # Keeps the container running
        volumeMounts:
        - name: old-pvc
          mountPath: /data/old
        - name: new-pvc
          mountPath: /data/old
      volumes:
      - name: old-pvc
        persistentVolumeClaim:
          claimName: rlcraft-minecraft-minecraft-datadir # Name of your existing PVC you want to migrate
      - name: new-pvc
        persistentVolumeClaim:
          claimName: old-pvc # Target pvcs name