apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
  labels:
    name: home-assistant
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: home-assistant
  sources:
    - repoURL: https://github.com/kubelize/kube-projects
      targetRevision: dev
      path: base/incubator/home-assistant/deploy
    - repoURL: http://pajikos.github.io/home-assistant-helm-chart/
      targetRevision:  0.2.100
      chart: home-assistant
      helm:
        valuesObject:
          service:
            type: LoadBalancer