apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch
spec:
  source:
    helm:
      valuesObject:
        minecraftServer:
          motd: §b💀
          maxTickTime: 60000
          difficulty: hard
          whitelist: McKency, icykhaye, ispolell, NekoCho, CellCraft, premiumching
          icon: "https://raw.githubusercontent.com/kubelize/kube-projects/refs/heads/dev/environments/home-mck/inventory/src/assets/minecraft-rlcraft-icon.png"
          maxPlayers: 10
          jvmXXOpts: "-XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M"
          modUrls:
           - https://mediafilez.forgecdn.net/files/5987/126/XaerosWorldMap_1.39.2_Forge_1.12.jar
           - https://mediafilez.forgecdn.net/files/3672/570/DarknessLib-1.12.2-1.1.2.jar
           - https://mediafilez.forgecdn.net/files/3425/511/Grue-1.12.2-1.8.1.jar
           - https://mediafilez.forgecdn.net/files/5998/289/voicechat-forge-1.12.2-2.5.27.jar
           - https://mediafilez.forgecdn.net/files/6012/809/Xaeros_Minimap_24.7.1_Forge_1.12.jar
          autoCurseForge:
            overridesSkipExisting: true
          extraPorts:
            - name: voipport
              containerPort: 24454
              protocol: UDP
              service:
                enabled: true
                embedded: true
                port: 24454
                targetPort: 24454
              ingress:
                enabled: false
        serviceAnnotations:
          "lbipam.cilium.io/ips": "192.168.1.233"
          

          
