apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch
spec:
  source:
    helm:
      valuesObject:
        minecraftServer:
          serviceAnnotations:
            "lbipam.cilium.io/ips": "192.168.1.233"
          motd: §b💀
          maxTickTime: 60000
          difficulty: hard
          whitelist: McKency, icykhaye, ispolell, NekoCho, CellCraft, premiumching
          icon: "https://raw.githubusercontent.com/kubelize/kube-projects/refs/heads/dev/environments/home-mck/inventory/src/assets/minecraft-rlcraft-icon.png"
          maxPlayers: 10
          autoCurseForge:
            includeMods:
              - "https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map"
              - "https://www.curseforge.com/minecraft/mc-mods/grue"
              - "https://www.curseforge.com/minecraft/mc-mods/darknesslib"
              - "https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat"

          

          
