apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch
spec:
  source:
    helm:
      valuesObject:
        minecraftServer:
          serviceAnnotations:
            "lbipam.cilium.io/ips": "192.168.1.231"
          motd: §b❄
          maxTickTime: 60000
          difficulty: normal
          levelSeed: "757067671151835873"
          whitelist: McKency, icykhaye, ispolell, NekoCho
          icon: "https://raw.githubusercontent.com/kubelize/kube-projects/refs/heads/dev/environments/home-mck/inventory/src/assets/minecraft-christmas-tree.png"
          viewDistance: 16
          memory: 4096M
        resources:
          requests:
            memory: 4096Mi
          limits:
            memory: 8192Mi
          

          
