apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch
spec:
  source:
    helm:
      valuesObject:
        minecraftServer:
          motd: §b❄
          maxTickTime: 60000
          difficulty: normal
          levelSeed: "757067671151835873"
          whitelist: McKency, icykhaye, ispolell, NekoCho
          icon: "https://raw.githubusercontent.com/kubelize/kube-projects/refs/heads/dev/environments/home-mck/inventory/src/assets/minecraft-christmas-tree.png"
          viewDistance: 16

          
