---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cf-api-token
  namespace: minecraft
spec:
  encryptedData:
    cf-api-key: AgCJtaBXrVsqAzJRJWedY8APD5KE+jRvI4x+hLM14KsPzzdI8CE7Uo4KKZNK3N4mcdlP3/3XLytdz4laLygh5U/32viaNMB5lYsGatb5QMfUyl8aCQISb7jlfm3Ow93u72am5QpHm0BkE5EAtY4cjR73ZnvMvGznVSJdWpt1EJEpNA2b1Q4rMVjY58Nb/Ax4MoloMiblFmdNf5gCSMiGrQH8vVTPHvcdbaYPXEzBqruKpv/SUhU1V4HUdQu1p77i8QAzOCa44mg/YEzaMdgkSmatYShpCvZabRN6COqNLIQK4E3V0YED1yi0xnjOBEzk2GjreoW/EOpr+ss3Utpv+J362/rtPpewdboSyYBir4cdzUw0CaiQgTEifAX9ztR5Az41Tcqlz0vl1c8m8wGo14o00wVxz9+Aphf0UALi3HaEzM/AMaHAxMUK6yjVtpDULMnGzQ1f6rxfHQvvLSEYChTN/73Ij9jCVk36kgoCCklDmsHM5P/wgi2Ht66XExVLc8M4az9oawa201Usegxx+WOLCQAbPZNrddgTx59sJ+GjJpwEEnILyJIdSoMajGv/B+M4/jgeC9rx/Bb6ej1rVz6BEHbSwEPkhY9q4ZiWTLxuSIU5Q6wImJdUySBdKhg1bZ4G4OgRN+xLZBcwdTpOxkIV74wSkIHChIjR9t5j5W+evDvUxEVMx54nRy9cgCewmL7jdW519ouNLQdZx1hg1oWBoY3eH/Xr7oNOty04RZyXKvhl4EM=
  template:
    metadata:
      creationTimestamp: null
      name: cf-api-token
      namespace: minecraft
    type: Opaque
