apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # projects stable
  
  # projects incubator
  - ../../projects/incubator/webservices/nextcloud-dev/
  - ../../projects/incubator/gameservers/web-rcon-dev-dhe/
  - ../../projects/incubator/webservices/wikijs/
  - ../../projects/incubator/gameservers/atm9-itzg/
  - ../../projects/incubator/webservices/jellyfin/

patches:
  - target:
      kind: Application
      name: wikijs
    path: config/values/wikijs-test/values.yaml
  - target:
      kind: Application
      name: nextcloud-test
    path: config/values/nextcloud-test/values.yaml