---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cf-api-token
  namespace: minecraft
spec:
  encryptedData:
    cf-api-key: AgBI/kGpsXubmifruY6dT9E/T9NP1SV5cQzq/FVEK+/w3PJmAh7dTPGZT9CfA9zdkj/fqyenQ6XFejUofQzY+p2LfKOAnZy2aI+HjBc0vx6fE9xOKTruHjyD3hsSVf5FR+6m/Jag4bnXxjzomCaB5fMbGlQtE7l461xbxmEp3PVDG48ZvEcq+8aN+y1PQ9SaQngpP5TD6exYesSqMVeSqSQd6tBBesj/k0e4lMhgnksXjRNwF9nBYgr1X3hxm2BvPYvxMEsApszMxOxgVdt+uIzHxo3S8vXgXBiSv2pm1G1MHNbMc5bbFhFbHIXO/te1yYOwlzvl/ancPAYt6ed1AtKHAqzE5u7Pw8C/z7W//BxgbJaCUFBmDUSWgpD3Z95io7Eawh73O5OMXAOuWYEa0Lj1zrj8yi1Emgx2g6Aa4JmaTjMtAS8oA3zffE2GFyV1nM9xI6EA/914vsZg0aTfeswYwCvc4v9hIKu9Ki4kmojAMUo+1FbBC0bbe8qgrlf5nBG859Uo6k+X/+dWoP19ScSJin5WNC20hpueU2cl/jwErANwazh9siLJOy7kAkIp0I+FfR34UTQIAVvmaywWBOOhXrDeWcb0WS0TCwTiAygN9kttYA/a8KWZh57X50+zqliKZFZ/gjOFtw5BSaHtUgQSy//XapulrFVxNP6xGxDGML4W9BwXC1MV20xMA8q/3TSqRAEBf86UNfBXEbZg6DqVxFTIhU8dpLlXp8ICjFaUXt5Gq9U=
  template:
    metadata:
      creationTimestamp: null
      name: cf-api-token
      namespace: minecraft
    type: Opaque
