apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-nginx-claim
  namespace: test-nginx
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi