---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-admin-credentials
  namespace: keycloak
spec:
  encryptedData:
    password: AgA6H1Hek7ZNK0IV4K1JKdPw8jkdhUjtLhP6gTtXctpSaSkuUjGMgYzgGFQkeduJyN/F3MjaE9qJIHlrW4lTuoGglu1VNABE/8Oy7S5QGjBcELB+mhza7LX8M+mSbw1aip4OC0yFALUV1lSZmL72raqoAtU4t1BmbyMBYF7UdpDqD6jNU1mthJAb7ArlO6fhxMi8Z7OuUqebe3+1TuAQY0k25fWhOboCy1gcITMjVhvDg/eb4D3E0gjj6yr5mncRBJ256lPqJqWvJLeUOgvtLaFeokK9ekBpLLH85BXgbJSfvWmOXmHn/7MfFezG8J3L+d1J+FGFsj2a33lf+Cmkc0lvopq7muu2PNrHMwG5sXjHi6J7JbGNZ7u/qVrGEEW2BAaIxW9u7DT/dABTKSw1kUPylV9uXOEV4hnWzlAZQChOgDjcvpmuswCaMiV18E2alXNuPRwbKfPSifw5shrCazwJNJoU6EGt0irZJSypXE/gq+Of6X2R09uQeUiTocMGvErYkPejL9NhRCXBGtvbSqecvTBF2g0HFHUeWXvG31KNglzszcDWZcuic41k13rgf1dzeRrCx6SK0sDnCaN7FM4Ng1ZvrA4phj8N1pufJjl60zrcJ1FEQDjInXzmAFbGtantlJWkMYBTcmN/aj2v6qUWuiv9UCgPVyRqgTbQuj9MZarybRj9Whnu3iYPvOe8cbdXmT1geQvZogiaOPzFia+O0j0KSidHT8z7
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-admin-credentials
      namespace: keycloak
    type: Opaque
