apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets-binding
  namespace: keycloak
subjects:
  - kind: ServiceAccount
    name: tf-runner  # Service account used by tf-runner
    namespace: flux-system  # Namespace where tf-runner is deployed
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
