apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: keycloak
  namespace: flux-system
spec:
  path: 00_base/incubator/keycloak/modules/
  interval: 1h0m0s
  retryInterval: 0h30m0s
  approvePlan: auto
  sourceRef:
    kind: GitRepository
    name: keycloak
    namespace: flux-system