apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 

  # incubator
  # - ../../../base/incubator/rickroll-heyya-immobilien-ch/
  - ../../../base/incubator/home-assistant/
  - ../../../base/incubator/pihole/
  # - ../../../base/stable/gameservers/minecraft-skyblock/
  # - ../../../base/stable/gameservers/minecraft-hardcore/

  # stable
  # - ../../../base/stable/nextcloud/
  # - ../../../base/stable/gameservers/sdtd/
  # - ../../../base/stable/gameservers/conan-exiles/

- secrets/


patches:
  - path: ./patches/pihole-config.yaml
    target:
      kind: Application
      name: pihole
