apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 

  # incubator
  - ../../../base/incubator/home-assistant/
  - ../../../base/incubator/pihole/

  # stable
  - ../../../base/stable/nextcloud/
  # - ../../../base/stable/gameservers/sdtd/
  # - ../../../base/stable/gameservers/conan-exiles/
  - ../../../base/stable/gameservers/minecraft/vanilla/
  - ../../../base/stable/uptime-kuma/

  # secrets
  - secrets/

patches:
  - path: ./patches/pihole-config.yaml
    target:
      kind: Application
      name: pihole
  - path: ./patches/vanilla-minecraft.yaml
    target:
      kind: Application
      name: vanilla-minecraft
  - path: ./patches/nextcloud-values.yaml
    target:
      kind: Application
      name: nextcloud
