apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 

  # incubator
  # - ../../../base/incubator/rickroll-heyya-immobilien-ch/
  # - ../../../base/incubator/helloworld/
  # - ../../../base/incubator/keycloak/
  # - ../../../base/incubator/home-assistant/
  # - ../../../base/stable/gameservers/minecraft-skyblock/
  # - ../../../base/stable/gameservers/minecraft-hardcore/

  # stable
  # - ../../../base/stable/nextcloud/
  # - ../../../base/stable/gameservers/sdtd/
  # - ../../../base/stable/gameservers/conan-exiles/

  # secrets
  - secrets/minecraft-rcon-password.yaml
  - secrets/cf-api-token.yaml

  # patches:
  #   - path: ./patches/example/example.yaml
