---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wikijs-postgresql
  namespace: kubelize-internal-wiki
spec:
  encryptedData:
    postgresql-password: AgAwBzTJ0tOTusr/ZsaNUDIGSDpiQXLLVODWPH06FsuQGsOFbFsLTgBD47tFTDV3kbcJ41L9KOlAZOnId3iZ54+68LO1CzYlXK9syQOthV1ObM73iecDuj2ESEVQdHtUHHaBOOhP/Y4/MLwiKDp8JAHsX4MKYL7Iv8HDmH4fqPpZiS4PXL6ymOXRtJaWimBfiGAtYG6touWMaQvutyWTH7oB/z/lnIb9hFWwB3xKfwPWStOJ7Rp8+1IpDDp9+m/UwiXuNDe7vN9h9jmvIRRMYYu+67kA5SL93+gZp8nIdqiASSh7n6kVfrmn+SZzwS1dNNpZgw1wb3/IVCXjYZdKSkQLMo7auXY1wIpFxDarIzgrg754+zZAjPSuXq5AlSOOX8EA2aSOcw7seTN29DH/G99bp5eCL0ynDl8TYjGsdkhA0fnhX+XGlXrGuIW48qrMJT3HgyvuncEsFctBskgpcQ5+Qtf7ta0l0/65VCqeyiY33LMTFbXOziB9YbkyUG12Rtw9s5spexZeT0ysEFCKwujJUPFCCijWcU5aWhnBs/WI00qVL6F4KE3a1kTqo8YwXUbCHnO3ZHoQt0AWgLerr4Vp0XYWQwX2w8pfr0YhKWMee+FjbpOCfz6sZgF9ir04OYjtLhBOBpdppFV84PZvWBN/HLY4L2nJbhZQbWKO6NVlPtjzi6DeHmlIRXUImsHlscWLtHnDqrQZVrJv
  template:
    metadata:
      creationTimestamp: null
      name: wikijs-postgresql
      namespace: kubelize-internal-wiki
    type: Opaque
