apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test-nginx
  name: test-nginx
  labels:
    app: test-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-nginx
  template:
    metadata:
      labels:
        app: test-nginx
    spec:
      containers:
       - name: test-nginx
         image: nginx
         ports:
          - containerPort: 80
            name: http
         volumeMounts:
          - mountPath: usr/share/nginx/html
            name: test-nginx-volume
         resources:
           limits:
             cpu: 1000m
             memory: 1Gi
           requests:
             cpu: 1000m
             memory: 1Gi 
      volumes:
       - name: test-nginx-volume
         persistentVolumeClaim:
           claimName: test-nginx-claim 