apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-nginx-claim
  namespace: test-nginx
  annotations: 
    kubevirt.io/provisionOnNode: prod-svc-270224
spec:
  storageClassName: kubevirt-hostpath-provisioner
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi