apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraria
  labels:
    app: terraria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terraria
  template:
    metadata:
      labels:
        app: terraria
    spec:
      initContainers:
        - name: init-permissions
          image: busybox
          command: ["sh", "-c", "mkdir -p /home/terra/.local/share/Terraria && chown -R 1000:1000 /home/terra"]
          volumeMounts:
            - mountPath: /home/terra/.local/share/Terraria
              name: terraria-data
      containers:
      - name: terraria
        image: kubelize/terraria:0.1.3
        ports:
        - containerPort: 7777
        volumeMounts:
        - name: terraria-data
          mountPath: /home/terra/.local/share/Terraria
        - name: config-volume
          mountPath: /home/terra/serversettings.txt
          subPath: serversettings.txt
      volumes:
      - name: terraria-data
        persistentVolumeClaim:
          claimName: terraria-data
      - name: config-volume
        configMap:
          name: terraria-settings