apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wikijs-dev
spec:
  destination:
    namespace: internal-wiki
  source:
    helm:
      valuesObject:
        replicaCount: 1
        revisionHistoryLimit: 10
        image:
          repository: requarks/wiki
          imagePullPolicy: IfNotPresent
        imagePullSecrets: []
        nameOverride: ""
        fullnameOverride: "wikijs-dev"
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
        startupProbe:
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 60
          httpGet:
            path: /healthz
            port: http
        podAnnotations: {}
        podSecurityContext: {}
        securityContext:
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
        service:
          type: ClusterIP
          port: 80
        ingress:
          enabled: false
          className: ""
          annotations: {}
          hosts:
            - host: wiki.minikube.local
              paths:
                - path: "/"
                  pathType: Prefix

          tls: []
        resources: {}
        nodeSelector: {}
        tolerations: []
        affinity: {}
        volumeMounts: []
        volumes: []
        sideload:
          enabled: false
          repoURL: https://github.com/Requarks/wiki-localization
          env: []
        postgresql:
          enabled: true
          fullnameOverride: "kubelize-wiki-dev"
          postgresqlUser: postgres
          postgresqlDatabase: wiki
          replication:
            enabled: false
          persistence:
            enabled: true
            storageClass: "longhorn"
            accessMode: ReadWriteOnce
            size: 100Gi
