apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terraria
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - repoURL: https://github.com/kubelize/kube-projects
      path: base/stable/gameservers/terraria/farfaraway/deploy
      targetRevision: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: terraria