apiVersion: v1
kind: Service
metadata:
  name: multipaper-master-proxy
  labels:
    helm.sh/chart: multipaper-0.1.0
    app.kubernetes.io/name: multipaper-master
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.18.2-63"
spec:
  type: NodePort
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
      name: proxy
  selector:
    app.kubernetes.io/name: multipaper-master
    app.kubernetes.io/instance: release-name