apiVersion: v1
kind: ConfigMap
metadata:
  name: multipaper-pufferfish
  labels:
    helm.sh/chart: multipaper-0.1.0
    app.kubernetes.io/name: multipaper
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.18.2-63"
data:
  pufferfish.yml: |
    # Pufferfish Configuration
    # Check out Pufferfish Host for maximum performance server hosting: https://pufferfish.host
    # Join our Discord for support: https://discord.gg/reZw4vQV9H
    # Download new builds at https://ci.pufferfish.host/job/Pufferfish
    info:
      version: '1.0'
    inactive-goal-selector-throttle: true
    enable-async-mob-spawning: false
    enable-books: true