apiVersion: v1
kind: ConfigMap
metadata:
  name: terraria-settings
  namespace: terraria
data:
  serversettings.txt: |
    maxplayers=16
    port=7777
    motd=Welcome to the Terraria server!
    autocreate=3
    difficulty=2
    world=/home/terra/.local/share/Terraria/Worlds/The_Big_Flats.wld
