apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraria
  labels:
    app: terraria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terraria
  template:
    metadata:
      labels:
        app: terraria
    spec:
      containers:
      - name: terraria
        image: kubelize/terraria:0.0.4
        ports:
        - containerPort: 7777
        volumeMounts:
        - name: terraria-world
          mountPath: /home/terra/.local/share/Terraria
        - name: config-volume
          mountPath: /home/terra/.local/share/Terraria/ServerSettings.txt
          subPath: ServerSettings.txt
      volumes:
      - name: terraria-world
        persistentVolumeClaim:
          claimName: terraria-world
      - name: config-volume
        configMap:
          name: terraria-server-settings