apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraria
  labels:
    app: terraria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terraria
  template:
    metadata:
      labels:
        app: terraria
    spec:
      containers:
      - name: terraria
        image: ryshe/terraria:latest
        ports:
        - containerPort: 7777
        env:
        - name: WORLD_FILENAME
          value: The_Big_Flats.wld
        volumeMounts:
        - name: terraria-world
          mountPath: /root/.local/share/Terraria/Worlds
      volumes:
      - name: terraria-world
        persistentVolumeClaim:
          claimName: terraria-world
