apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terraria-world
  namespace: terraria
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn