apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-nginx
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/kubelize/kube-projects
      path: 00_base/incubator/test-nginx/deploy
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: test-nginx