apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch
spec:
  source:
    helm:
      valuesObject:
        ingress:
          tls:
            - secretName: nextcloud-tls
              hosts:
                - drive.kubelize.com
        nextcloud:
          host: drive.kubelize.com
        mariadb:
          primary:
            persistence:
              size: 10Gi
        persistence:
          size:
            10Gi
