- op: add
  path: "/spec/sources/1/helm/valuesObject/ingress/tls"
  value:
    - secretName: nextcloud-tls
      hosts:
        - drive.kubelize.com
- op: add
  path: "/spec/sources/1/helm/valuesObject/nextcloud/host"
  value: drive.kubelize.com
- op: add
  path: "/spec/sources/1/helm/valuesObject/mariadb/primary/persistence/size"
  value: 10Gi
- op: add
  path: "/spec/sources/1/helm/valuesObject/persistence/size"
  value: 
    10Gi

