- op: add
  path: "/spec/source/helm/parameters/-"
  value:
    name: serviceDns.loadBalancerIP
    value: 10.130.5.231
- op: add
  path: "/spec/source/helm/parameters/-"
  value:
    name: serviceDns.type
    value: LoadBalancer
- op: add
  path: "/spec/source/helm/parameters/-"
  value: serviceDns.annotations
    name: lbipam.cilium.io/sharing-key
    value: "pihole"
- op: add
  path: "/spec/source/helm/valuesObject/dnsmasq/customDnsEntries"
  value:
    - address=/home-assistant/10.130.5.232
- op: add
  path: "/spec/source/helm/valuesObject/dnsmasq/customCnameEntries"
  value:
    - cname=home-assistant.home,home-assistant
