- op: add
  path: "/spec/sources/helm/parameters/-"
  value:
    name: serviceDns.loadBalancerIP
    value: 10.130.5.231
- op: add
  path: "/spec/sources/helm/parameters/-"
  value:
    name: serviceDns.type
    value: LoadBalancer
- op: replace
  path: "/spec/sources/helm/valuesObject/dnsmasq/customDnsEntries"
  value:
    - address=/home-assistant/10.130.5.232
- op: replace
  path: "/spec/sources/helm/valuesObject/dnsmasq/customCnameEntries"
  value:
    - cname=home-assistant.home,home-assistant
