- op: add
  path: "/spec/source/helm/valuesObject/virtualHost"
  value: home-dhe-pihole.teleport.kubelize.com
- op: add
  path: "/spec/source/helm/valuesObject/serviceDns"
  value:
    loadBalancerIP: 10.130.5.232
    type: LoadBalancer
    annotations:
      lbipam.cilium.io/sharing-key: pihole
- op: add
  path: "/spec/source/helm/valuesObject/dnsmasq/customDnsEntries"
  value:
    - address=/home-assistant/10.130.5.232
- op: add
  path: "/spec/source/helm/valuesObject/dnsmasq/customCnameEntries"
  value:
    - cname=home-assistant.home,home-assistant
