apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch
spec:
  source:
    helm:
      valuesObject:
        minecraftServer:
          serviceAnnotations:
            "lbipam.cilium.io/ips": "10.130.5.237"
          motd: §b💀
          maxTickTime: -1
          difficulty: hard
          whitelist: McKency, icykhaye, ispolell, NekoCho, CellCraft, premiumching
          icon: "https://raw.githubusercontent.com/kubelize/kube-projects/refs/heads/dev/environments/home-mck/inventory/src/assets/minecraft-rlcraft-icon.png"
          maxPlayers: 10
          autoCurseForge:
            includeMods:
              - projectID: 227083
                fileID: 3795316