apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch
spec:
  source:
    helm:
      valuesObject:
        minecraftServer:
          serviceAnnotations:
            "lbipam.cilium.io/ips": "10.130.5.235"
          motd: "Definitly not a spoopy server."
          maxTickTime: 60000
          difficulty: hard
          levelSeed: "757067671151835873"
          whitelist: Moffoso, Reitorii
          icon: "https://raw.githubusercontent.com/kubelize/kube-projects/refs/heads/dev/environments/home-dhe/inventory/src/assets/minecraft-spider-snow.jpg"
          viewDistance: 16

          
