apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ce-server-data
  namespace: ce-server-server
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi